/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pe.algoritmo.vidarte.views.elecciones;

import pe.algoritmo.vidarte.controllers.EleccionController;
import pe.algoritmo.vidarte.models.Eleccion;
import pe.algoritmo.vidarte.utils.Utilidades;
import pe.algoritmo.vidarte.utils.ValidadorCampos;

/**
 *
 * @author VIDARTE
 */
public class addEleccion extends javax.swing.JDialog {

    EleccionController control;

    public addEleccion(java.awt.Frame parent, boolean modal, EleccionController control) {
        super(parent, modal);
        initComponents();
        this.control = control;
        Utilidades.validarNumero(txtAnio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("AGREGAR");
        jLabel19.setToolTipText("");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 380, 30));

        jLabel16.setText("TITULO");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 30));
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 50, 310, 30));

        btnRegistrar.setBackground(new java.awt.Color(102, 255, 102));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 120, 40));

        jLabel17.setText("AÑO");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 30));
        jPanel1.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 100, 30));
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 110, 30));

        jLabel18.setText("FECHA");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 130, 30));

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        boolean validador = ValidadorCampos.validarCampos(txtTitulo, txtAnio, txtFecha);
        if (validador) {
            Eleccion eleccion = new Eleccion();
            eleccion.setTitulo(txtTitulo.getText());
            eleccion.setAnio(Integer.parseInt(txtAnio.getText()));
            eleccion.setFechaElecciones(txtFecha.getText());
            
            control.registrar(eleccion);

            javax.swing.JOptionPane.showMessageDialog(this, "Registro exitoso.", "Registro", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe completar todos los campos.", "Campos incompletos", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
