/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.algoritmo.vidarte.views.votaciones;
import javax.swing.JTextField;

import pe.algoritmo.vidarte.controllers.DistritoController;
import pe.algoritmo.vidarte.controllers.EleccionController;
import pe.algoritmo.vidarte.controllers.MesaController;
import pe.algoritmo.vidarte.models.Distrito;
import pe.algoritmo.vidarte.models.Eleccion;
import pe.algoritmo.vidarte.models.Mesa;
import pe.algoritmo.vidarte.utils.Utilidades;

/**
 *
 * @author VIDARTE
 */
public class addVotacion extends javax.swing.JFrame {

    private DistritoController controldis;
    private MesaController controlmesa;
    private EleccionController controlelec;

    public addVotacion() {
        initComponents();
        controlelec = new EleccionController();
        controldis = new DistritoController();
        controlmesa = new MesaController();
        
        for (String eleccion : controlelec.getNombresElecciones()) {
            cbEleccion.addItem(eleccion);
        }

        for (String distrito : controldis.getNombresDistritos()) {
            cbDistrito.addItem(distrito);
        }

        for (int i = 1; i <= 100; i++) {
            cbSeccion.addItem(String.valueOf(i));
        }

        Utilidades.validarNumero(txtPsoe);
        Utilidades.validarNumero(txtFO);
        Utilidades.validarNumero(txtPP);
        Utilidades.validarNumero(txtPACMA);
        Utilidades.validarNumero(txtPcte);
        Utilidades.validarNumero(txtPUM);
        Utilidades.validarNumero(txtVOX);
        Utilidades.validarNumero(txtPUEDE);
        Utilidades.validarNumero(txtAEEV);
        Utilidades.validarNumero(txtRC);
        Utilidades.validarNumero(txtSUMAR);
        Utilidades.validarNumero(txtABSTE);
        Utilidades.validarNumero(txtBLANC);
        Utilidades.validarNumero(txtNULOS);

    }

    private int sumarVotos() {
        int total = 0;
        total += Integer.parseInt(txtPsoe.getText());
        total += Integer.parseInt(txtFO.getText());
        total += Integer.parseInt(txtPP.getText());
        total += Integer.parseInt(txtPACMA.getText());
        total += Integer.parseInt(txtPcte.getText());
        total += Integer.parseInt(txtPUM.getText());
        total += Integer.parseInt(txtVOX.getText());
        total += Integer.parseInt(txtPUEDE.getText());
        total += Integer.parseInt(txtAEEV.getText());
        total += Integer.parseInt(txtRC.getText());
        total += Integer.parseInt(txtSUMAR.getText());
        total += Integer.parseInt(txtABSTE.getText());
        total += Integer.parseInt(txtBLANC.getText());
        total += Integer.parseInt(txtNULOS.getText());
        return total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPsoe = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtFO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPACMA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPcte = new javax.swing.JTextField();
        txtPUM = new javax.swing.JTextField();
        txtVOX = new javax.swing.JTextField();
        txtPUEDE = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAEEV = new javax.swing.JTextField();
        txtRC = new javax.swing.JTextField();
        txtSUMAR = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtABSTE = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtBLANC = new javax.swing.JTextField();
        txtNULOS = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbDistrito = new javax.swing.JComboBox<>();
        cbEleccion = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cbSeccion = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        cbMesa = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DISTRITO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, 30));

        txtPsoe.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPsoe.setText("0");
        jPanel1.add(txtPsoe, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 50, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 10, 160));

        jLabel2.setText("FO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 30));

        txtFO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFO.setText("0");
        jPanel1.add(txtFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 50, 30));

        jLabel3.setText("PP");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 50, 30));

        txtPP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPP.setText("0");
        jPanel1.add(txtPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 50, 30));

        jLabel4.setText("PACMA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 50, 30));

        txtPACMA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPACMA.setText("0");
        jPanel1.add(txtPACMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 50, 30));

        jLabel5.setText("PCTE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 50, 30));

        jLabel6.setText("PUM");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 50, 30));

        jLabel7.setText("VOX");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 50, 30));

        jLabel8.setText("PUEDE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 50, 30));

        txtPcte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPcte.setText("0");
        jPanel1.add(txtPcte, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 50, 30));

        txtPUM.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPUM.setText("0");
        jPanel1.add(txtPUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 50, 30));

        txtVOX.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVOX.setText("0");
        jPanel1.add(txtVOX, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 50, 30));

        txtPUEDE.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPUEDE.setText("0");
        jPanel1.add(txtPUEDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 50, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 10, 160));

        jLabel9.setText("AEEV");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 50, 30));

        jLabel10.setText("RC");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 50, 30));

        jLabel11.setText("SUMAR");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 50, 30));

        txtAEEV.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAEEV.setText("0");
        jPanel1.add(txtAEEV, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 50, 30));

        txtRC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRC.setText("0");
        jPanel1.add(txtRC, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 50, 30));

        txtSUMAR.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSUMAR.setText("0");
        jPanel1.add(txtSUMAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 50, 30));

        jLabel12.setText("ABSTE");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 50, 30));

        txtABSTE.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtABSTE.setText("0");
        jPanel1.add(txtABSTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 50, 30));

        jLabel13.setText("BLANC");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 50, 30));

        txtBLANC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBLANC.setText("0");
        jPanel1.add(txtBLANC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 50, 30));

        txtNULOS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNULOS.setText("0");
        jPanel1.add(txtNULOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 50, 30));

        jLabel14.setText("NULOS");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 50, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 132, 400, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 323, 400, 10));

        jLabel15.setText("PSOE");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 50, 30));

        jLabel16.setText("ELECCION");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 30));

        jPanel1.add(cbDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 100, 30));

        jPanel1.add(cbEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 330, 30));

        jLabel17.setText("SECCION");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 60, 30));

        jPanel1.add(cbSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 60, 30));

        jLabel18.setText("MESA");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 40, 30));

        cbMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" }));
        jPanel1.add(cbMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 60, 30));

        btnRegistrar.setBackground(new java.awt.Color(102, 255, 102));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 210, 40));

        jLabel19.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("ACTA ELECTORAL");
        jLabel19.setToolTipText("");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, 400, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        int response = javax.swing.JOptionPane.showConfirmDialog(this, "¿Está seguro de registrar los " + sumarVotos() + " votos?", "Confirmación", javax.swing.JOptionPane.YES_NO_OPTION);
        if (response == javax.swing.JOptionPane.YES_OPTION) {
            Distrito distrito = controldis.getDistritoByNombre(cbDistrito.getSelectedItem().toString());
            int seccion = Integer.parseInt(cbSeccion.getSelectedItem().toString());
            String mesa = cbMesa.getSelectedItem().toString();
            Eleccion eleccion = controlelec.getEleccionById(cbEleccion.getSelectedIndex() + 1);
            Mesa m = new Mesa(0, distrito, seccion, mesa);
            javax.swing.JOptionPane.showMessageDialog(this, "Registro exitoso");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Registro cancelado");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addVotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addVotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addVotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addVotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addVotacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbDistrito;
    private javax.swing.JComboBox<String> cbEleccion;
    private javax.swing.JComboBox<String> cbMesa;
    private javax.swing.JComboBox<String> cbSeccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtABSTE;
    private javax.swing.JTextField txtAEEV;
    private javax.swing.JTextField txtBLANC;
    private javax.swing.JTextField txtFO;
    private javax.swing.JTextField txtNULOS;
    private javax.swing.JTextField txtPACMA;
    private javax.swing.JTextField txtPP;
    private javax.swing.JTextField txtPUEDE;
    private javax.swing.JTextField txtPUM;
    private javax.swing.JTextField txtPcte;
    private javax.swing.JTextField txtPsoe;
    private javax.swing.JTextField txtRC;
    private javax.swing.JTextField txtSUMAR;
    private javax.swing.JTextField txtVOX;
    // End of variables declaration//GEN-END:variables
}
