/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.algoritmo.vidarte.views.votaciones;

import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.function.BiPredicate;

import javax.swing.JTable;

import pe.algoritmo.vidarte.controllers.DistritoController;
import pe.algoritmo.vidarte.controllers.EleccionController;
import pe.algoritmo.vidarte.controllers.VotacionController;
import pe.algoritmo.vidarte.models.Votacion;
import pe.algoritmo.vidarte.tables.VotacionDistritoTableModel;
import pe.algoritmo.vidarte.tables.VotacionTableModel;
import pe.algoritmo.vidarte.utils.Ordenamiento;
import pe.algoritmo.vidarte.utils.Utilidades;
import pe.algoritmo.vidarte.utils.Lista.Lista;

/**
 *
 * @author VIDARTE
 */
public class votaciones extends javax.swing.JFrame {

    private final VotacionController control;;
    private final EleccionController controlelec;
    private final DistritoController controldis;

    private JTable tablaImprimir;

    private static votaciones instance = null;

    /**
     * Creates new form votaciones
     */
    private votaciones() {
        initComponents();
        
        // Inicializar controladores
        controlelec = new EleccionController();
        controldis = new DistritoController();
        control = new VotacionController();

        // Cargar datos
        tablaImprimir = new JTable();
        this.tablaElecciones.setAutoCreateRowSorter(true);

        cargarDatos();

        // Cargar combobox
        for (String eleccion : controlelec.getNombresElecciones()) {
            cbEleccion.addItem(eleccion);
        }

        for (String distrito : controldis.getNombresDistritos()) {
            cbDistrito.addItem(distrito);
        }

        for (int i = 1; i <= 100; i++) {
            cbSeccion.addItem(String.valueOf(i));
        }
    }

    public static votaciones getInstance() {
        if (instance == null) {
            instance = new votaciones();
        }
        return instance;
    }

    private void cargarDatos(){
        VotacionTableModel modelito = new VotacionTableModel(control.getVotaciones());
        tablaImprimir.setModel(modelito);
        VotacionDistritoTableModel modelo = new VotacionDistritoTableModel(control.getVotaciones());
        this.tablaElecciones.setModel(modelo);
        System.out.println("Datos cargados");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaElecciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cbEleccion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbDistrito = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cbSeccion = new javax.swing.JComboBox<>();
        btnFiltrar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cbOrden = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaElecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaElecciones.setRowHeight(25);
        jScrollPane1.setViewportView(tablaElecciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 840, 270));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setText("VOTACIONES REGISTRADOS");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 30));

        btnEliminar.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 120, 30));

        btnAgregar.setBackground(new java.awt.Color(102, 255, 102));
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 130, 30));

        jLabel16.setText("ELECCION");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, 30));

        jPanel1.add(cbEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 380, 30));

        jLabel2.setText("DISTRITO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 60, 30));

        cbDistrito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS" }));
        jPanel1.add(cbDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 100, 30));

        jLabel17.setText("SECCION");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 70, 30));

        cbSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS" }));
        jPanel1.add(cbSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, 30));

        btnFiltrar.setBackground(new java.awt.Color(255, 153, 102));
        btnFiltrar.setText("FILTRAR");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, 90, 30));

        jLabel18.setText("ORDEN");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 50, 30));

        cbOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIN ORDEN", "MAYOR A MENOR", "MENOR A MAYOR" }));
        jPanel1.add(cbOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, 30));

        jButton1.setText("REPORTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnFiltrarActionPerformed
        int eleccion = cbEleccion.getSelectedIndex() + 1;
        int distrito = cbDistrito.getSelectedItem().equals("TODOS") ? -1 : cbDistrito.getSelectedIndex();
        int seccion = cbSeccion.getSelectedItem().equals("TODOS") ? -1
                : Integer.parseInt(cbSeccion.getSelectedItem().toString());
        int orden = cbOrden.getSelectedIndex();

        Lista<Votacion> votacionesFiltradas = Utilidades.listafiltrada(control.getVotaciones(), eleccion, distrito,
                seccion);
        if (orden == 1) {
            BiPredicate<Votacion, Votacion> predicado = (Votacion v1,
                    Votacion v2) -> v1.getResultado().getElectores() < v2.getResultado().getElectores();
            votacionesFiltradas = Ordenamiento.burbuja(votacionesFiltradas, predicado);
        } else if (orden == 2) {
            BiPredicate<Votacion, Votacion> predicado = (Votacion v1,
                    Votacion v2) -> v1.getResultado().getElectores() > v2.getResultado().getElectores();
            votacionesFiltradas = Ordenamiento.burbuja(votacionesFiltradas, predicado);
        }
        VotacionTableModel modeloimprimir = new VotacionTableModel(votacionesFiltradas);
        VotacionDistritoTableModel modelo = new VotacionDistritoTableModel(votacionesFiltradas);
        tablaElecciones.setModel(modelo);
        tablaImprimir.setModel(modeloimprimir);
    }// GEN-LAST:event_btnFiltrarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarActionPerformed
        addVotacion agregar = new addVotacion(this, true);
        agregar.setVisible(true);
        cargarDatos();
    }// GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tablaElecciones.getSelectedRow();
        if (fila == -1) {
            return;
        }
        int id = (int) tablaElecciones.getValueAt(fila, 0);
        System.out.println(id);
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea eliminar esta acta electoral?", "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            if (control.eliminarById(id)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Acta electoral eliminada correctamente.");
            }
        }
        cargarDatos();
    }// GEN-LAST:event_btnEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        PdfReportGenerator generator = new PdfReportGenerator();
        try {
            String nombreReporte = "reporte_votaciones_" + new SimpleDateFormat("yyyyMMdd_HHmm").format(new Date()) + ".pdf";
            generator.generatePdfReport(this.tablaImprimir, nombreReporte);
            javax.swing.JOptionPane.showMessageDialog(this, "Reporte generado correctamente!");
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JComboBox<String> cbDistrito;
    private javax.swing.JComboBox<String> cbEleccion;
    private javax.swing.JComboBox<String> cbOrden;
    private javax.swing.JComboBox<String> cbSeccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaElecciones;
    // End of variables declaration//GEN-END:variables
}
