/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.algoritmo.vidarte.views.votaciones;

import pe.algoritmo.vidarte.controllers.DistritoController;
import pe.algoritmo.vidarte.controllers.EleccionController;
import pe.algoritmo.vidarte.controllers.MesaController;
import pe.algoritmo.vidarte.controllers.VotacionController;
import pe.algoritmo.vidarte.models.Votacion;
import pe.algoritmo.vidarte.tables.VotacionDistritoTableModel;
import pe.algoritmo.vidarte.utils.Utilidades;
import pe.algoritmo.vidarte.utils.Lista.Lista;

/**
 *
 * @author VIDARTE
 */
public class votaciones extends javax.swing.JFrame {

    private final VotacionController control;;
    private final EleccionController controlelec;
    private final DistritoController controldis;
    private final MesaController controlmesa;
    
    private static votaciones instance = null;
    /**
     * Creates new form votaciones
     */
    private votaciones() {
        initComponents();
        control = new VotacionController();
        VotacionDistritoTableModel modelo = new VotacionDistritoTableModel(control.getVotaciones());
        this.tablaElecciones.setModel(modelo);
        
        controlelec = new EleccionController();
        controldis = new DistritoController();
        controlmesa = new MesaController();
        
        for (String eleccion : controlelec.getNombresElecciones()) {
            cbEleccion.addItem(eleccion);
        }

        for (String distrito : controldis.getNombresDistritos()) {
            cbDistrito.addItem(distrito);
        }

        for (int i = 1; i <= 100; i++) {
            cbSeccion.addItem(String.valueOf(i));
        }
    }

    public static votaciones getInstance() {
        if (instance == null) {
            instance = new votaciones();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaElecciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cbEleccion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbDistrito = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cbSeccion = new javax.swing.JComboBox<>();
        btnFiltrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaElecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaElecciones.setRowHeight(25);
        jScrollPane1.setViewportView(tablaElecciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 820, 270));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setText("VOTACIONES REGISTRADOS");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 220, 60));

        btnEliminar.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminar.setText("ELIMINAR");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 120, -1));

        btnAgregar.setBackground(new java.awt.Color(102, 255, 102));
        btnAgregar.setText("AGREGAR");
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 130, -1));

        jLabel16.setText("ELECCION");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 120, 30));

        jPanel1.add(cbEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 380, 30));

        jLabel2.setText("DISTRITO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 80, 30));

        cbDistrito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS" }));
        jPanel1.add(cbDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 120, 30));

        jLabel17.setText("SECCION");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 60, 30));

        cbSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS" }));
        jPanel1.add(cbSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 90, 30));

        btnFiltrar.setBackground(new java.awt.Color(255, 153, 102));
        btnFiltrar.setText("FILTRAR");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        int eleccion = cbEleccion.getSelectedIndex() + 1;
        int distrito = cbDistrito.getSelectedItem().equals("TODOS") ? -1 : cbDistrito.getSelectedIndex();
        int seccion = cbSeccion.getSelectedItem().equals("TODOS") ? -1 : Integer.parseInt(cbSeccion.getSelectedItem().toString());

        Lista<Votacion> votacionesFiltradas = Utilidades.listafiltrada(control.getVotaciones(), eleccion, distrito, seccion);
        VotacionDistritoTableModel modelo = new VotacionDistritoTableModel(votacionesFiltradas);
        tablaElecciones.setModel(modelo);
    }//GEN-LAST:event_btnFiltrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(votaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(votaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(votaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(votaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new votaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JComboBox<String> cbDistrito;
    private javax.swing.JComboBox<String> cbEleccion;
    private javax.swing.JComboBox<String> cbSeccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaElecciones;
    // End of variables declaration//GEN-END:variables
}
