/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.algoritmo.vidarte.views.distritos;

import pe.algoritmo.vidarte.controllers.DistritoController;
import pe.algoritmo.vidarte.models.Distrito;
import pe.algoritmo.vidarte.tables.DistritoTableModel;
import pe.algoritmo.vidarte.utils.Utilidades;
import pe.algoritmo.vidarte.utils.ValidadorCampos;
import pe.algoritmo.vidarte.utils.Lista.Lista;

/**
 *
 * @author VIDARTE
 */
public class distritos extends javax.swing.JFrame {

    private DistritoController control;
    private static distritos instance = null;
    /**
     * Creates new form distritos
     */
    private distritos() {
        initComponents();
        control = new DistritoController();
        cargarDistritos();
    }

    public static distritos getInstance() {
        if (instance == null) {
            instance = new distritos();
        }
        return instance;
    }

    public void cargarDistritos(){
        DistritoTableModel modelo = new DistritoTableModel(control.getDistritos());
        this.tablaElecciones.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaElecciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtDistrito = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaElecciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaElecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaElecciones.setRowHeight(25);
        jScrollPane1.setViewportView(tablaElecciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 350, 190));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setText("DISTRITOS REGISTRADOS");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 120, -1));

        btnAgregar.setBackground(new java.awt.Color(102, 255, 102));
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 120, -1));

        jLabel15.setText("Distrito");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 60, 30));

        txtDistrito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(txtDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 110, 30));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tablaElecciones.getSelectedRow();
        if (fila == -1) {
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea eliminar este distrito?", "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            if (control.eliminarById(fila+1)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Distrito eliminado correctamente.");
            }
        }
        cargarDistritos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        addDistrito agregar = new addDistrito(this, true, control);
        agregar.setVisible(true);
        cargarDistritos();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        boolean validador = ValidadorCampos.validarCampos(txtDistrito);
        if (validador) {
            Lista<Distrito> distritos = control.getDistritos();
            Lista<Distrito> distritosFiltrados = Utilidades.buscarDistrito(distritos, txtDistrito.getText());
            DistritoTableModel modelo = new DistritoTableModel(distritosFiltrados);
            this.tablaElecciones.setModel(modelo);
        } else {
            cargarDistritos();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaElecciones;
    private javax.swing.JTextField txtDistrito;
    // End of variables declaration//GEN-END:variables
}
